//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class AspWebFormReply : IEntityBase
    {
        public AspWebFormReply()
        {
            this.AspWebFormReplies1 = new HashSet<AspWebFormReply>();
        }
    
        public int Id { get; set; }
        public int AspWfRId { get; set; }
        public string AspWfRText { get; set; }
        public string AspWfRTitle { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int UserId { get; set; }
        public int AspWfId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
        public bool IsActive { get; set; }
        public string AspWfRSku { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public string LanguageName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> AspWebFormReplies_AspWfRId { get; set; }
        public string Reply { get; set; }
        public int TID { get; set; }
        public Nullable<int> AspNetUsers_Id { get; set; }
        public Nullable<int> AspWebform_Id { get; set; }
        public Nullable<int> tbh_SubDepartments_Id { get; set; }
        public Nullable<int> AspWebFormReply1_Id { get; set; }
        public Nullable<int> tbh_Departments_Id { get; set; }
        public Nullable<int> tbh_Language_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<AspWebFormReply> AspWebFormReplies1 { get; set; }
        public virtual AspWebFormReply AspWebFormReply1 { get; set; }
        public virtual AspWebform AspWebform { get; set; }
        public virtual tbh_Departments tbh_Departments { get; set; }
        public virtual tbh_Language tbh_Language { get; set; }
        public virtual tbh_SubDepartments tbh_SubDepartments { get; set; }
    }
}
