//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class Cart : IEntityBase
    {
        public Cart()
        {
            this.Carts1 = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public int RecordId { get; set; }
        public string CartId { get; set; }
        public int ProductID { get; set; }
        public int Count { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> Cart_RecordId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PictureUrl { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public Nullable<int> DeliveryMethodId { get; set; }
        public string ClientSecret { get; set; }
        public string PaymentIntentId { get; set; }
        public decimal ShippingPrice { get; set; }
        public string Reply { get; set; }
        public int TID { get; set; }
        public Nullable<int> Cart2_Id { get; set; }
        public Nullable<int> tbh_Products_Id { get; set; }
    
        public virtual ICollection<Cart> Carts1 { get; set; }
        public virtual Cart Cart1 { get; set; }
        public virtual tbh_Products tbh_Products { get; set; }
    }
}
