//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryItem
    {
        public int Id { get; set; }
        public int DepartmentID { get; set; }
        public int CategoryID { get; set; }
        public int Name { get; set; }
    }
}
