//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class FilePath : IEntityBase
    {
        public int Id { get; set; }
        public int FilePathId { get; set; }
        public string FileName { get; set; }
        public int FileType { get; set; }
        public string UserId { get; set; }
    }
}
