//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class NLReply : IEntityBase
    {
        public NLReply()
        {
            this.NLReplies1 = new HashSet<NLReply>();
        }
    
        public int Id { get; set; }
        public int NLRId { get; set; }
        public string NLRText { get; set; }
        public string NLRTitle { get; set; }
        public int NLId { get; set; }
        public string MenuURL { get; set; }
        public string FullImageUrl { get; set; }
        public bool IsActive { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> NLReplies_NLRId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Reply { get; set; }
        public int TID { get; set; }
        public Nullable<int> AspNetUsers_Id { get; set; }
        public Nullable<int> NLReply1_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<NLReply> NLReplies1 { get; set; }
        public virtual NLReply NLReply1 { get; set; }
    }
}
