//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class PostTag : IEntityBase
    {
        public int Id { get; set; }
        public int ThreadId { get; set; }
        public string TagId { get; set; }
        public bool Checked { get; set; }
        public string pstid { get; set; }
        public string Reply { get; set; }
        public int TID { get; set; }
        public Nullable<int> tbh_Tag_Id { get; set; }
    
        public virtual tbh_Tag tbh_Tag { get; set; }
        public virtual Thread Thread { get; set; }
    }
}
