//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class PostVideo : IEntityBase
    {
        public int Id { get; set; }
        public string VideoUrl { get; set; }
        public string VideoThumbnail { get; set; }
        public string pstid { get; set; }
        public string VideoSiteName { get; set; }
        public string Reply { get; set; }
        public int TID { get; set; }
    }
}
