//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class ProfileModel : IEntityBase
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FullImageUrl { get; set; }
        public bool IsActive { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string IsEmailVerified { get; set; }
        public string IsTwoFactorOn { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> EmailLinkDate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string UserProfile { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte[] UserPhoto { get; set; }
        public byte[] image { get; set; }
        public byte[] PersonalPhoto { get; set; }
        public int LoginCount { get; set; }
    }
}
