//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Subscribe : IEntityBase
    {
        public int Id { get; set; }
        public decimal SubscribeId { get; set; }
        public int UserId { get; set; }
        public string name { get; set; }
        public string emailid { get; set; }
        public Nullable<int> AspNetUsers_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
