//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_PaymentTypes : IEntityBase
    {
        public tbh_PaymentTypes()
        {
            this.tbh_Payments = new HashSet<tbh_Payments>();
        }
    
        public int Id { get; set; }
        public int PayTypeID { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbh_Payments> tbh_Payments { get; set; }
    }
}
