//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Services : IEntityBase
    {
        public int Id { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MenuURL { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public string Title { get; set; }
        public Nullable<int> Importance { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Ancestor { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> tbh_Departments_Id { get; set; }
    
        public virtual tbh_Departments tbh_Departments { get; set; }
    }
}
