//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Blog : IEntityBase
    {
        public int Id { get; set; }
        public int BlogID { get; set; }
        public string Heading { get; set; }
        public string Picture { get; set; }
        public string SubTitle { get; set; }
        public string Details { get; set; }
        public System.DateTime PublishOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
