//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_ProductSize : IEntityBase
    {
        public int Id { get; set; }
        public Nullable<decimal> DepartmentID { get; set; }
        public Nullable<decimal> SubDepartmentID { get; set; }
        public Nullable<decimal> PID { get; set; }
        public Nullable<decimal> ProductID { get; set; }
        public Nullable<decimal> colorid { get; set; }
        public string size { get; set; }
        public Nullable<decimal> UnitsInstock { get; set; }
        public decimal sizeid { get; set; }
    }
}
