//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbh_OrderDetails
    {
        public int OrderDetailsID { get; set; }
        public int OrderId { get; set; }
        public int ProductID { get; set; }
        public double UnitPrice { get; set; }
        public int Quantity { get; set; }
        public string Coupon { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> tbh_Products_Id { get; set; }
    
        public virtual tbh_Products tbh_Products { get; set; }
        public virtual tbl_Order tbl_Order { get; set; }
    }
}
