//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_ReadPost : IEntityBase
    {
        public int Id { get; set; }
        public int RPId { get; set; }
        public Nullable<int> ThreadId { get; set; }
        public Nullable<int> ReplyId { get; set; }
        public string ThreadText { get; set; }
        public string ThreadTitle { get; set; }
        public string ReplyText { get; set; }
        public string ReplyTitle { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> AspNetUsers_Id { get; set; }
        public Nullable<int> tbh_Replies_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tbh_Replies tbh_Replies { get; set; }
        public virtual Thread Thread { get; set; }
    }
}
