//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Products : IEntityBase
    {
        public tbh_Products()
        {
            this.Carts = new HashSet<Cart>();
            this.tbh_OrderDetails = new HashSet<tbh_OrderDetails>();
            this.tbh_productpic = new HashSet<tbh_productpic>();
            this.tbh_Products1 = new HashSet<tbh_Products>();
            this.tbh_ProductsDetails = new HashSet<tbh_ProductsDetails>();
            this.tbh_RecentlyViews = new HashSet<tbh_RecentlyViews>();
            this.tbh_Reviews = new HashSet<tbh_Reviews>();
            this.tbh_Wishlist = new HashSet<tbh_Wishlist>();
            this.Wishlists = new HashSet<Wishlist>();
        }
    
        public int Id { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
        public string Name { get; set; }
        public string ProductsURL { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AddedBy { get; set; }
        public string Content { get; set; }
        public string ShortDescription { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public string FullImageUrl { get; set; }
        public string AltText { get; set; }
        public Nullable<bool> AddBadge { get; set; }
        public string OfferTitle { get; set; }
        public string OfferBadgeClass { get; set; }
        public Nullable<int> TotalRating { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public string Picture4 { get; set; }
        public string IsFor { get; set; }
        public string PermissionTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Status { get; set; }
        public bool Main { get; set; }
        public string Description { get; set; }
        public string ZoomUrl { get; set; }
        public string ProductType { get; set; }
        public string ProductBrand { get; set; }
        public int ManufacturerId { get; set; }
        public Nullable<int> tbh_Products_ProductID { get; set; }
        public int CategoryItems { get; set; }
        public Nullable<int> tbh_Category_Id { get; set; }
        public Nullable<int> tbh_SubCategory_Id { get; set; }
        public Nullable<int> tbh_Departments_Id { get; set; }
        public Nullable<int> tbh_Products2_Id { get; set; }
        public Nullable<int> tbh_Shop_Id { get; set; }
        public Nullable<int> tbh_SubDepartments_Id { get; set; }
        public Nullable<int> Producer_Id { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual tbh_Category tbh_Category { get; set; }
        public virtual tbh_Departments tbh_Departments { get; set; }
        public virtual ICollection<tbh_OrderDetails> tbh_OrderDetails { get; set; }
        public virtual ICollection<tbh_productpic> tbh_productpic { get; set; }
        public virtual ICollection<tbh_Products> tbh_Products1 { get; set; }
        public virtual tbh_Products tbh_Products2 { get; set; }
        public virtual tbh_Shop tbh_Shop { get; set; }
        public virtual tbh_SubCategory tbh_SubCategory { get; set; }
        public virtual tbh_SubDepartments tbh_SubDepartments { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<tbh_ProductsDetails> tbh_ProductsDetails { get; set; }
        public virtual ICollection<tbh_RecentlyViews> tbh_RecentlyViews { get; set; }
        public virtual ICollection<tbh_Reviews> tbh_Reviews { get; set; }
        public virtual ICollection<tbh_Wishlist> tbh_Wishlist { get; set; }
        public virtual ICollection<Wishlist> Wishlists { get; set; }
    }
}
