//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_ProductCart : IEntityBase
    {
        public int Id { get; set; }
        public decimal cartid { get; set; }
        public string FullImageUrl { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> TotalRating { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public string brand { get; set; }
        public Nullable<decimal> total { get; set; }
        public string username { get; set; }
        public Nullable<decimal> ProductID { get; set; }
    }
}
