//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Comments : IEntityBase
    {
        public tbh_Comments()
        {
            this.tbh_CommentLike = new HashSet<tbh_CommentLike>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string UserName { get; set; }
        public string Body { get; set; }
        public int NetLikeCount { get; set; }
        public bool Deleted { get; set; }
        public string PageId { get; set; }
        public string pstid { get; set; }
        public string ParentReplyId { get; set; }
    
        public virtual ICollection<tbh_CommentLike> tbh_CommentLike { get; set; }
    }
}
