//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_ProductCoupon : IEntityBase
    {
        public int Id { get; set; }
        public decimal CouponID { get; set; }
        public string CouponName { get; set; }
        public Nullable<decimal> MinCartValue { get; set; }
        public Nullable<decimal> CouponPercent { get; set; }
    }
}
