//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Reviews : IEntityBase
    {
        public int Id { get; set; }
        public int ReviewID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Review1 { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> AspNetUser_Id { get; set; }
        public Nullable<int> tbh_Products_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tbh_Products tbh_Products { get; set; }
    }
}
