//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_FrontSlider : IEntityBase
    {
        public int Id { get; set; }
        public int FsID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
        public string Name { get; set; }
        public string FsURL { get; set; }
        public string Content { get; set; }
        public string ShortDescription { get; set; }
        public string FullImageUrl { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public string AltText { get; set; }
        public string BtnText { get; set; }
        public string OfferTag { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Status { get; set; }
        public Nullable<int> tbh_Departments_Id { get; set; }
        public Nullable<int> tbh_SubDepartments_Id { get; set; }
    
        public virtual tbh_Departments tbh_Departments { get; set; }
        public virtual tbh_SubDepartments tbh_SubDepartments { get; set; }
    }
}
