//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_CompanyStory : IEntityBase
    {
        public int Id { get; set; }
        public int CStoryID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Picture { get; set; }
        public string EmbedCode { get; set; }
        public string OtherDetails { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
