//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_ProductsDetails : IEntityBase
    {
        public int Id { get; set; }
        public int PDetailsID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
        public Nullable<int> PID { get; set; }
        public string Features { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string SType { get; set; }
        public string size { get; set; }
        public Nullable<decimal> UnitsInstock { get; set; }
        public Nullable<int> tbh_Products_Id { get; set; }
    
        public virtual tbh_Products tbh_Products { get; set; }
    }
}
