//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_PostLike : IEntityBase
    {
        public int Id { get; set; }
        public string PostLikeId { get; set; }
        public string Username { get; set; }
        public bool Like { get; set; }
        public bool Dislike { get; set; }
        public Nullable<int> ThreadId { get; set; }
        public Nullable<int> PostId { get; set; }
        public string pstid { get; set; }
        public int Age { get; set; }
        public string KnownAs { get; set; }
        public string PhotoUrl { get; set; }
        public string City { get; set; }
        public Nullable<int> Thread_Id { get; set; }
        public Nullable<int> Thread_Id1 { get; set; }
        public Nullable<int> Thread1_Id { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Thread Thread { get; set; }
        public virtual Thread Thread1 { get; set; }
        public virtual Thread Thread2 { get; set; }
        public virtual Thread Thread3 { get; set; }
    }
}
