//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Album : IEntityBase
    {
        public int Id { get; set; }
        public int AlbumID { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public System.DateTime PublishOn { get; set; }
        public Nullable<int> ViewsCount { get; set; }
    }
}
