//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_productpic : IEntityBase
    {
        public tbh_productpic()
        {
            this.tbh_productpic1 = new HashSet<tbh_productpic>();
        }
    
        public int Id { get; set; }
        public int picid { get; set; }
        public Nullable<decimal> PID { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string FullImageUrl { get; set; }
        public string ColorImageUrl { get; set; }
        public string colorname { get; set; }
        public Nullable<decimal> DepartmentID { get; set; }
        public Nullable<decimal> SubDepartmentID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Main { get; set; }
        public Nullable<int> tbh_productpic_picid { get; set; }
        public Nullable<int> tbh_productpic2_Id { get; set; }
        public Nullable<int> tbh_Products_Id { get; set; }
    
        public virtual ICollection<tbh_productpic> tbh_productpic1 { get; set; }
        public virtual tbh_productpic tbh_productpic2 { get; set; }
        public virtual tbh_Products tbh_Products { get; set; }
    }
}
