//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_SettingMeta : IEntityBase
    {
        public tbh_SettingMeta()
        {
            this.tbh_SettingMeta1 = new HashSet<tbh_SettingMeta>();
        }
    
        public int Id { get; set; }
        public int SMetaID { get; set; }
        public string TableName { get; set; }
        public string MetaKey { get; set; }
        public string MetaValue { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModied { get; set; }
        public Nullable<int> tbh_SettingMeta2_Id { get; set; }
    
        public virtual ICollection<tbh_SettingMeta> tbh_SettingMeta1 { get; set; }
        public virtual tbh_SettingMeta tbh_SettingMeta2 { get; set; }
    }
}
