//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Membership : IEntityBase
    {
        public tbh_Membership()
        {
            this.PhotoDtoes = new HashSet<PhotoDto>();
        }
    
        public int Id { get; set; }
        public int MSliderID { get; set; }
        public string Title { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Username { get; set; }
        public string PhotoUrl { get; set; }
        public int Age { get; set; }
        public string KnownAs { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastActive { get; set; }
        public string Gender { get; set; }
        public string Introduction { get; set; }
        public string LookingFor { get; set; }
        public string Interests { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<PhotoDto> PhotoDtoes { get; set; }
    }
}
