//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_SubCategory : IEntityBase
    {
        public tbh_SubCategory()
        {
            this.tbh_Products = new HashSet<tbh_Products>();
        }
    
        public int Id { get; set; }
        public int SubCategoryID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> tbh_Category_Id { get; set; }
    
        public virtual tbh_Category tbh_Category { get; set; }
        public virtual ICollection<tbh_Products> tbh_Products { get; set; }
    }
}
