//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_Media : IEntityBase
    {
        public int Id { get; set; }
        public int MediaID { get; set; }
        public string Name { get; set; }
        public string MediaUrl { get; set; }
        public string alt { get; set; }
        public string title { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModied { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
