//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tbh_MenuPermission : IEntityBase
    {
        public int Id { get; set; }
        public int MPID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool IsCreate { get; set; }
        public bool IsRead { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsDelete { get; set; }
    }
}
