//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class tblVideo : IEntityBase
    {
        public tblVideo()
        {
            this.tblVideos1 = new HashSet<tblVideo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> tblVideo_Id { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public bool IsActive { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string VideoTitle { get; set; }
        public Nullable<int> AspNetUser_Id { get; set; }
        public Nullable<int> tbh_Departments_Id { get; set; }
        public Nullable<int> tbh_SubDepartments_Id { get; set; }
        public Nullable<int> tblVideo2_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tbh_Departments tbh_Departments { get; set; }
        public virtual tbh_SubDepartments tbh_SubDepartments { get; set; }
        public virtual ICollection<tblVideo> tblVideos1 { get; set; }
        public virtual tblVideo tblVideo1 { get; set; }
    }
}
