//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class Thread : IEntityBase
    {
        public Thread()
        {
            this.PostTags = new HashSet<PostTag>();
            this.tbh_PostLike = new HashSet<tbh_PostLike>();
            this.tbh_PostLike1 = new HashSet<tbh_PostLike>();
            this.tbh_PostLike2 = new HashSet<tbh_PostLike>();
            this.tbh_PostLike3 = new HashSet<tbh_PostLike>();
            this.tbh_ReadPost = new HashSet<tbh_ReadPost>();
            this.tbh_Replies = new HashSet<tbh_Replies>();
            this.Threads1 = new HashSet<Thread>();
        }
    
        public int Id { get; set; }
        public int ThreadId { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string ThreadText { get; set; }
        public string ThreadTitle { get; set; }
        public string MenuURL { get; set; }
        public string FullImageUrl { get; set; }
        public bool IsActive { get; set; }
        public string GetUserName { get; set; }
        public string UserProfile_Id { get; set; }
        public string MemberProfile { get; set; }
        public Nullable<int> Thread_ThreadId { get; set; }
        public string ThreadSKu { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public string LanguageName { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Reply { get; set; }
        public int TID { get; set; }
        public Nullable<int> AspNetUsers_Id { get; set; }
        public Nullable<int> tbh_Departments_Id { get; set; }
        public Nullable<int> tbh_Language_Id { get; set; }
        public Nullable<int> tbh_SubDepartments_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<PostTag> PostTags { get; set; }
        public virtual tbh_Departments tbh_Departments { get; set; }
        public virtual tbh_Language tbh_Language { get; set; }
        public virtual ICollection<tbh_PostLike> tbh_PostLike { get; set; }
        public virtual ICollection<tbh_PostLike> tbh_PostLike1 { get; set; }
        public virtual ICollection<tbh_PostLike> tbh_PostLike2 { get; set; }
        public virtual ICollection<tbh_PostLike> tbh_PostLike3 { get; set; }
        public virtual ICollection<tbh_ReadPost> tbh_ReadPost { get; set; }
        public virtual ICollection<tbh_Replies> tbh_Replies { get; set; }
        public virtual tbh_SubDepartments tbh_SubDepartments { get; set; }
        public virtual ICollection<Thread> Threads1 { get; set; }
        public virtual Thread Thread1 { get; set; }
    }
}
