//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProgram.Edm
{
    using MainProgram.Core.Data;
    using System;
    using System.Collections.Generic;

    public partial class Wishlist : IEntityBase
    {
        public int Id { get; set; }
        public int WishlistID { get; set; }
        public int UserId { get; set; }
        public int ProductID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> AspNetUser_Id { get; set; }
        public Nullable<int> tbh_Products_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tbh_Products tbh_Products { get; set; }
    }
}
